
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstadoCuenta", targetNamespace = "http://Servicios/", wsdlLocation = "classpath:/src/main/resources/wsdl/EstadoCuenta.wsdl")
public class EstadoCuenta_Service
    extends Service
{

    private final static URL ESTADOCUENTA_WSDL_LOCATION;
    private final static WebServiceException ESTADOCUENTA_EXCEPTION;
    private final static QName ESTADOCUENTA_QNAME = new QName("http://Servicios/", "EstadoCuenta");

    static {
        URL url = null;
        WebServiceException e = null;
        url = EstadoCuenta_Service.class.getClassLoader().getResource("wsdl/EstadoCuenta.wsdl");
        ESTADOCUENTA_WSDL_LOCATION = url;
        ESTADOCUENTA_EXCEPTION = e;
    }

    public EstadoCuenta_Service() {
        super(__getWsdlLocation(), ESTADOCUENTA_QNAME);
    }

    public EstadoCuenta_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTADOCUENTA_QNAME, features);
    }

    public EstadoCuenta_Service(URL wsdlLocation) {
        super(wsdlLocation, ESTADOCUENTA_QNAME);
    }

    public EstadoCuenta_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTADOCUENTA_QNAME, features);
    }

    public EstadoCuenta_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadoCuenta_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstadoCuenta
     */
    @WebEndpoint(name = "EstadoCuentaPort")
    public EstadoCuenta getEstadoCuentaPort() {
        return super.getPort(new QName("http://Servicios/", "EstadoCuentaPort"), EstadoCuenta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadoCuenta
     */
    @WebEndpoint(name = "EstadoCuentaPort")
    public EstadoCuenta getEstadoCuentaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "EstadoCuentaPort"), EstadoCuenta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTADOCUENTA_EXCEPTION!= null) {
            throw ESTADOCUENTA_EXCEPTION;
        }
        return ESTADOCUENTA_WSDL_LOCATION;
    }

}
